#version: '3'
services:
  web:
    build: .
    ports:
      - "80:8080"
    deploy:
      resources:
          limits:
            cpus: '1'
            memory: 1024M
          reservations:
            cpus: '0.50'
            memory: 256M