openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: API documentation for the exposed endpoints

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /v1/status:
    get:
      summary: Return the status of the application
      responses:
        '200':
          description: A JSON object containing the status information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'

  /db:
    post:
      summary: Insert a new user into the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Alice
                email:
                  type: string
                  example: alice@example.com
      responses:
        '200':
          description: A JSON object containing a success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Database initialized and new row inserted

    get:
      summary: Retrieve all users from the database
      responses:
        '200':
          description: A JSON object containing a list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Alice
                        email:
                          type: string
                          example: alice@example.com

components:
  schemas:
    StatusResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        request_id:
          type: string
          example: "12345"
        ip:
          type: string
          example: "192.168.1.1"
        user_agent:
          type: string
          example: "Mozilla/5.0"
        user_method:
          type: string
          example: "GET"
    SampleMessageResponse:
      type: object
      properties:
        code:
          type: integer
          example: 15
        message:
          type: string
          example: Data Structures and Algorithms