name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint  --disable=broad-exception-caught $(git ls-files '*.py' | grep -v 'test/')
    #- name: Executing Unit Tests
    #  run: |
    #    cd app
    #    python -m unittest discover -v
